Repository HYF-Class22/Group-2-Job-Board-FrontEnd, pull requests merged in 2024-09, with the labels that each got.

#13 Add fundamental features to homepage
  index.html
  src/Api.js
  src/components/JobsPage.css
  src/components/JobsPage.jsx
  src/main.jsx
Labels: feature

#15 add sorting by company name in ascending and descending order
  src/components/JobsPage.jsx
  src/components/Sort/Sort.css
  src/components/Sort/Sort.jsx
Labels: feature

#17 add delete job page
  src/components/DeleteJob/DeleteJob.css
  src/components/DeleteJob/DeleteJob.jsx
Labels: feature

#19 add Search bar
  src/components/JobsPage.jsx
  src/components/Search/Search.css
  src/components/Search/Search.jsx
Labels: feature

#22 readded index.html
  index.html
  src/components/DeleteJob/DeleteJob.jsx
Labels: bug, feature

#31 delete sorting types (ascending and descending)
  src/components/JobsPage.jsx
  src/components/Sort/Sort.jsx
Labels: bug

#32 added interview date on homepage
  src/components/JobsPage.css
  src/components/JobsPage.jsx
  src/components/Sort/Sort.jsx
Labels: feature

#43 added locally sorting function
  src/components/JobsPage.jsx
  src/components/Sort/Sort.jsx
Labels: feature

#45 Link Search to BE
  src/Api.js
  src/components/JobsPage.jsx
  src/components/Search/Search.jsx
Labels: feature
